apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-demo"
        vault.hashicorp.com/agent-inject-secret-config.txt: "secret/data/eso-demo"
      labels:
        app: {{ .Release.Name }}

    spec:
      serviceAccountName: vault-demo
      containers:
        - name: nginx

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 80

          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: environment

            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: message

          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
