apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-demo
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-store
    kind: SecretStore

  target:
    name: eso-demo
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: eso-demo
        property: username

    - secretKey: password
      remoteRef:
        key: eso-demo
        property: password
